// dashboard/docs/.vitepress/theme/components/LineChart.vue
<script setup lang="ts">
// Values over weeks, drawn like the dashboard's LineChart: one featured
// student, the class (dashed) and an optional band. Percentages use a fixed
// 0-100 axis, other units a rounded maximum. null leaves a gap: "no data
// that week" is not 0.
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useLang } from '../composables'

const props = withDefaults(
  defineProps<{
    ticks: string[]
    featured: (number | null)[]
    classLine?: (number | null)[]
    band?: { lo: (number | null)[]; hi: (number | null)[] }
    ariaLabel: string
    height?: number
    unit?: string
  }>(),
  { height: 170, unit: 'pct' },
)

const { pct, num } = useLang()
const box = ref<HTMLElement>()
const width = ref(300)
let observer: ResizeObserver | undefined
onMounted(() => {
  if (!box.value) return
  width.value = box.value.clientWidth || 300
  observer = new ResizeObserver(([entry]) => (width.value = entry.contentRect.width || 300))
  observer.observe(box.value)
})
onBeforeUnmount(() => observer?.disconnect())

const M = { top: 10, right: 10, bottom: 22, left: 38 }
const n = computed(() => props.ticks.length)
const plotW = computed(() => Math.max(0, width.value - M.left - M.right))
const plotH = computed(() => props.height - M.top - M.bottom)
const x = (i: number) => M.left + (n.value > 1 ? (plotW.value * i) / (n.value - 1) : plotW.value / 2)
function niceMax(v: number) {
  if (v <= 0) return 1
  const p = 10 ** Math.floor(Math.log10(v))
  return [1, 2, 2.5, 5, 10].map((m) => m * p).find((c) => c >= v) ?? 10 * p
}
const yMax = computed(() => {
  if (props.unit === 'pct') return 100
  const all = [...props.featured, ...(props.classLine ?? []), ...(props.band?.hi ?? [])].filter((v): v is number => v != null)
  return niceMax(Math.max(1, ...all))
})
const ticksY = computed(() => [0, yMax.value / 2, yMax.value])
const tickLabel = (v: number) => (props.unit === 'pct' ? pct(v) : num(v, v < 10 ? 1 : 0))
const y = (v: number) => M.top + plotH.value - (v / yMax.value) * plotH.value

function segments(values: (number | null)[]) {
  const parts: string[] = []
  let current = ''
  values.forEach((v, i) => {
    if (v == null) {
      if (current) parts.push(current)
      current = ''
    } else current += `${current ? 'L' : 'M'}${x(i).toFixed(1)},${y(v).toFixed(1)}`
  })
  if (current) parts.push(current)
  return parts
}

const bandPath = computed(() => {
  if (!props.band) return ''
  const { lo, hi } = props.band
  const idx = lo.map((_, i) => i).filter((i) => lo[i] != null && hi[i] != null)
  if (idx.length < 2) return ''
  const top = idx.map((i, k) => `${k ? 'L' : 'M'}${x(i).toFixed(1)},${y(hi[i]!).toFixed(1)}`).join('')
  const bottom = [...idx].reverse().map((i) => `L${x(i).toFixed(1)},${y(lo[i]!).toFixed(1)}`).join('')
  return `${top}${bottom}Z`
})
</script>

<template>
  <div ref="box">
    <svg class="chart" :width="width" :height="height" role="img" :aria-label="ariaLabel">
      <g v-for="v in ticksY" :key="v">
        <line :class="v === 0 ? 'baseline' : 'grid'" :x1="M.left" :x2="width - M.right" :y1="y(v)" :y2="y(v)" />
        <text class="tick" :x="M.left - 6" :y="y(v)" dy="0.32em" text-anchor="end">{{ tickLabel(v) }}</text>
      </g>
      <text
        v-for="(tick, i) in ticks"
        :key="`t${i}`"
        class="tick"
        :x="x(i)"
        :y="height - 5"
        text-anchor="middle"
      >{{ tick }}</text>
      <path v-if="bandPath" class="band" :d="bandPath" />
      <path v-for="(d, i) in classLine ? segments(classLine) : []" :key="`c${i}`" class="line-class" :d="d" />
      <path v-for="(d, i) in segments(featured)" :key="`f${i}`" class="line-featured" :d="d" />
      <template v-for="(v, i) in featured" :key="`d${i}`">
        <circle v-if="v != null" class="dot-featured" :cx="x(i)" :cy="y(v)" r="3.5" />
      </template>
    </svg>
  </div>
</template>

// dashboard/src/components/charts/LineChart.tsx
import { useState, type KeyboardEvent, type PointerEvent } from 'react';
import { useElementWidth } from '../../hooks/usePolling';
import { useI18n } from '../../i18n';

export interface LineSeries {
  key: string;
  label: string;
  /** CSS class that sets the stroke / fill colour (.series-1, .series-2). */
  className: string;
  /** null leaves a gap: "no data that week" is not 0%. */
  values: (number | null)[];
}

interface Props {
  /** Point labels along the x axis. */
  ticks: string[];
  /** Tooltip heading per point. */
  labels: string[];
  series: LineSeries[];
  ariaLabel: string;
  height?: number;
}

const MARGIN = { top: 14, right: 12, bottom: 24, left: 40 };
const Y_TICKS = [0, 25, 50, 75, 100];
const TICK_LABEL_WIDTH = 48;

/** Percentages (0-100) over time, one shared axis. Only for series that
 * share that unit -- never two different scales on one chart. */
export function LineChart({ ticks, labels, series, ariaLabel, height = 200 }: Props) {
  const { t, f } = useI18n();
  const [ref, width] = useElementWidth<HTMLDivElement>();
  const [active, setActive] = useState<number | null>(null);

  const n = ticks.length;
  const plotW = Math.max(0, width - MARGIN.left - MARGIN.right);
  const plotH = height - MARGIN.top - MARGIN.bottom;
  const step = n > 1 ? plotW / (n - 1) : 0;
  const x = (i: number) => MARGIN.left + (n > 1 ? step * i : plotW / 2);
  const y = (v: number) => MARGIN.top + plotH - (v / 100) * plotH;
  const tickEvery = step > 0 ? Math.max(1, Math.ceil(TICK_LABEL_WIDTH / step)) : 1;

  // Separate path segments around null values.
  const segments = (values: (number | null)[]) => {
    const parts: string[] = [];
    let current = '';
    values.forEach((v, i) => {
      if (v == null) {
        if (current) parts.push(current);
        current = '';
      } else {
        current += `${current ? 'L' : 'M'}${x(i)},${y(v)}`;
      }
    });
    if (current) parts.push(current);
    return parts;
  };

  const onPointerMove = (e: PointerEvent<SVGRectElement>) => {
    const box = e.currentTarget.getBoundingClientRect();
    const i = step > 0 ? Math.round((e.clientX - box.left) / step) : 0;
    setActive(Math.min(n - 1, Math.max(0, i)));
  };

  const onKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;
    e.preventDefault();
    setActive((current) => Math.min(n - 1, Math.max(0, (current ?? n - 1) + (e.key === 'ArrowLeft' ? -1 : 1))));
  };

  const tooltipX = active != null ? Math.min(Math.max(x(active), 90), width - 90) : 0;

  return (
    <div className="line-chart">
      <ul className="legend legend-inline">
        {series.map((s) => (
          <li key={s.key}>
            <span className={`line-key ${s.className}`} aria-hidden="true" />
            <span className="legend-label">{s.label}</span>
          </li>
        ))}
      </ul>
      <div
        ref={ref}
        className="column-chart"
        tabIndex={0}
        role="group"
        aria-label={`${ariaLabel}. ${t('chart.keyboardHint')}`}
        onKeyDown={onKeyDown}
        onFocus={() => setActive((current) => current ?? n - 1)}
        onBlur={() => setActive(null)}
        style={{ height }}
      >
        {width > 0 && (
          <svg width={width} height={height} aria-hidden="true">
            {Y_TICKS.map((v) => (
              <g key={v}>
                <line className={v === 0 ? 'chart-baseline' : 'chart-gridline'} x1={MARGIN.left} x2={width - MARGIN.right} y1={y(v)} y2={y(v)} />
                <text className="chart-tick" x={MARGIN.left - 8} y={y(v)} dy="0.32em" textAnchor="end">
                  {f.pct(v)}
                </text>
              </g>
            ))}
            {ticks.map((tick, i) =>
              (n - 1 - i) % tickEvery === 0 ? (
                <text
                  key={i}
                  className="chart-tick"
                  x={x(i)}
                  y={height - 6}
                  textAnchor={i === n - 1 ? 'end' : i === 0 ? 'start' : 'middle'}
                >
                  {tick}
                </text>
              ) : null,
            )}
            {active != null && <line className="chart-crosshair" x1={x(active)} x2={x(active)} y1={MARGIN.top} y2={y(0)} />}
            {series.map((s) => (
              <g key={s.key} className={s.className}>
                {segments(s.values).map((d, i) => (
                  <path key={i} className="chart-line" d={d} />
                ))}
                {s.values.map((v, i) =>
                  // Points with no neighbour would be invisible as a line.
                  v != null && (active === i || s.values[i - 1] == null && s.values[i + 1] == null) ? (
                    <circle key={i} className="chart-dot" cx={x(i)} cy={y(v)} r={4} />
                  ) : null,
                )}
              </g>
            ))}
            <rect
              className="chart-hit"
              x={MARGIN.left - step / 2}
              y={MARGIN.top}
              width={plotW + step}
              height={plotH}
              onPointerMove={onPointerMove}
              onPointerLeave={() => setActive(null)}
            />
          </svg>
        )}
        {active != null && (
          <div className="chart-tooltip" style={{ left: tooltipX, top: MARGIN.top }} role="status">
            <span>{labels[active]}</span>
            {series.map((s) => (
              <span key={s.key} className="tooltip-row">
                <span className={`line-key ${s.className}`} aria-hidden="true" />
                <strong>{s.values[active] != null ? f.pct(s.values[active]!) : t('trend.noValue')}</strong>
                <span>{s.label}</span>
              </span>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
